import axios from "axios"

const api = axios.create({
  baseURL: "https://api.brawlstars.com/v1",
  headers: {
    authorization:
      "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImU3OTE0NDgyLWM3NWMtNDYxYy1iZDFmLWMyMWQwNWQwYjA1MSIsImlhdCI6MTYyNDU2NjU0OCwic3ViIjoiZGV2ZWxvcGVyLzcyNzJlN2I0LWY1NTctMmNiZS0xNTBkLWIxYWI4YWNkYWIzNSIsInNjb3BlcyI6WyJicmF3bHN0YXJzIl0sImxpbWl0cyI6W3sidGllciI6ImRldmVsb3Blci9zaWx2ZXIiLCJ0eXBlIjoidGhyb3R0bGluZyJ9LHsiY2lkcnMiOlsiNzYuNzYuMjEuMjEiXSwidHlwZSI6ImNsaWVudCJ9XX0.C7xcoww_bOA4EYV7TObL1yQDoXkLDb39Tz0Su7Kt4cOtaoGOrXzEio5A1LtMz63bJ0U_FSXwYwLvHh4e22W3sA",
    Accept: "application/json",
  },
})

export default api
